[env:adafruit_circuitplayground_m0]
platform = atmelsam
board = adafruit_circuitplayground_m0
framework = arduino
monitor_speed = 115200

build_flags = 
    -D USE_TINYUSB=0

lib_deps = 
    adafruit/Adafruit NeoPixel @ ^1.15.5